# Generated by Django 4.2.23 on 2025-08-02 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="inventory",
            name="cas_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="safety_data_sheet_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventory",
            name="storage_conditions",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
